### PR TITLE
Ability to disable auto-dismiss when tapping on background

### PR DESCRIPTION
**Pull request by kevin-hirsch**
I added a `BOOL` to be able to disable the auto-dismiss feature by tapping on the background view.
That would be cool if you could merge it to your master :)

### CODE REVIEW

**Comment by kevin-hirsch** [comment]
I also updated the podspec version to 1.2.0 for CocoaPods :)

**Comment by kevin-hirsch** [comment]
I also fix a compilation error because some properties were defined `messageBackgroundColorRGB`, `qqBackgroundColorRGB`, etc. and were used with leading capitals (`MessageBackgroundColorRGB`, `QQBackgroundColorRGB`, etc.)

**Comment by kevin-hirsch** [comment]
I also upgraded all `int` to `NSInteger`, `id` to `instancetype` to improve code safety for all architectures and made integration in Swift more easy :)

**Comment by mixdesign** [comment]
Good job @kevin-hirsch . Thank you for contributing.

**Comment by kevin-hirsch** [comment]
Nice! :)
Thanks to you for this great library! :+1:

**Pull request merged**
